sudo: required
dist: trusty
language: c
compiler:
- clang
- gcc
install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq nasm gettext libgtk-3-dev libncursesw5-dev libpci-dev libprocps-dev libgtk-3-0 libncursesw5 libprocps3 libpci3
script:
- mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_LIBCPUID=0 ..
