sudo: required
dist: trusty
language: c
compiler:
- clang
- gcc

before_install:
- curl http://download.opensuse.org/repositories/home:/X0rg/xUbuntu_14.04/Release.key | sudo apt-key add -
- echo "deb http://download.opensuse.org/repositories/home:/X0rg/xUbuntu_14.04/ /" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
install:
- sudo apt-get install -y -qq nasm gettext libgtk-3-dev libncursesw5-dev libcpuid13-dev libpci-dev libprocps-dev libgtk-3-0 libncursesw5 libcpuid13 libprocps3 libpci3
before_script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr ..
script:
- make
after_success:
- sudo make install
- sudo cpu-x --dump

notifications:
  slack:
    on_success: never
    on_failure: change
